[build]
  command = "mkdir -p assets/env && touch assets/env/app.env && flutter build web --release"
  publish = "build/web"

[[plugins]]
  package = "netlify-plugin-flutter"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200