[[plugins]]
  package = "netlify-plugin-flutter"

[build]
  # We use 'touch .env' to make sure the app finds the file, 
  # even if it's empty (we'll use Netlify UI for the real keys)
  command = "touch .env && flutter build web --release"
  publish = "build/web"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200